GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "image_url": "https://example.com/image.png",
    "price": 100
}

###

GET http://localhost:3000/products

### 

POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MTA3MjY4MzYsImV4cCI6MTcxMDcyNjg5Nn0.yHDC2PekBwbbIlNLQVBDji5s9oNznMWuvnE7Hh5rYck

{
    "items": [
        {
            "product_id": "09424707-dae0-4550-8ade-b4bea22fd8f4",
            "quantity": 2
        }
    ],
    "card_hash": "1234567890123456"
}

###

POST http://localhost:3000/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}
